// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: hazard/hazard.proto

package hazard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HazardDetection_DetectHazard_FullMethodName = "/hazard.HazardDetection/DetectHazard"
)

// HazardDetectionClient is the client API for HazardDetection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HazardDetectionClient interface {
	// Single RPC for detecting hazards
	DetectHazard(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
}

type hazardDetectionClient struct {
	cc grpc.ClientConnInterface
}

func NewHazardDetectionClient(cc grpc.ClientConnInterface) HazardDetectionClient {
	return &hazardDetectionClient{cc}
}

func (c *hazardDetectionClient) DetectHazard(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, HazardDetection_DetectHazard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HazardDetectionServer is the server API for HazardDetection service.
// All implementations must embed UnimplementedHazardDetectionServer
// for forward compatibility.
type HazardDetectionServer interface {
	// Single RPC for detecting hazards
	DetectHazard(context.Context, *ImageRequest) (*DetectionResponse, error)
	mustEmbedUnimplementedHazardDetectionServer()
}

// UnimplementedHazardDetectionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHazardDetectionServer struct{}

func (UnimplementedHazardDetectionServer) DetectHazard(context.Context, *ImageRequest) (*DetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectHazard not implemented")
}
func (UnimplementedHazardDetectionServer) mustEmbedUnimplementedHazardDetectionServer() {}
func (UnimplementedHazardDetectionServer) testEmbeddedByValue()                         {}

// UnsafeHazardDetectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HazardDetectionServer will
// result in compilation errors.
type UnsafeHazardDetectionServer interface {
	mustEmbedUnimplementedHazardDetectionServer()
}

func RegisterHazardDetectionServer(s grpc.ServiceRegistrar, srv HazardDetectionServer) {
	// If the following call pancis, it indicates UnimplementedHazardDetectionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HazardDetection_ServiceDesc, srv)
}

func _HazardDetection_DetectHazard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HazardDetectionServer).DetectHazard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HazardDetection_DetectHazard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HazardDetectionServer).DetectHazard(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HazardDetection_ServiceDesc is the grpc.ServiceDesc for HazardDetection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HazardDetection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hazard.HazardDetection",
	HandlerType: (*HazardDetectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectHazard",
			Handler:    _HazardDetection_DetectHazard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hazard/hazard.proto",
}
