// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: hazard/hazard.proto

package hazard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // Raw image bytes (JPEG/PNG)
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`                  // Optional GPS
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_hazard_hazard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hazard_hazard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_hazard_hazard_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ImageRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ImageRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type DetectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HazardType    string                 `protobuf:"bytes,1,opt,name=hazard_type,json=hazardType,proto3" json:"hazard_type,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // High=3, Medium=2, Low=1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_hazard_hazard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hazard_hazard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_hazard_hazard_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionResponse) GetHazardType() string {
	if x != nil {
		return x.HazardType
	}
	return ""
}

func (x *DetectionResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectionResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_hazard_hazard_proto protoreflect.FileDescriptor

const file_hazard_hazard_proto_rawDesc = "" +
	"\n" +
	"\x13hazard/hazard.proto\x12\x06hazard\"g\n" +
	"\fImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"p\n" +
	"\x11DetectionResponse\x12\x1f\n" +
	"\vhazard_type\x18\x01 \x01(\tR\n" +
	"hazardType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority2R\n" +
	"\x0fHazardDetection\x12?\n" +
	"\fDetectHazard\x12\x14.hazard.ImageRequest\x1a\x19.hazard.DetectionResponseB\tZ\a/hazardb\x06proto3"

var (
	file_hazard_hazard_proto_rawDescOnce sync.Once
	file_hazard_hazard_proto_rawDescData []byte
)

func file_hazard_hazard_proto_rawDescGZIP() []byte {
	file_hazard_hazard_proto_rawDescOnce.Do(func() {
		file_hazard_hazard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hazard_hazard_proto_rawDesc), len(file_hazard_hazard_proto_rawDesc)))
	})
	return file_hazard_hazard_proto_rawDescData
}

var file_hazard_hazard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hazard_hazard_proto_goTypes = []any{
	(*ImageRequest)(nil),      // 0: hazard.ImageRequest
	(*DetectionResponse)(nil), // 1: hazard.DetectionResponse
}
var file_hazard_hazard_proto_depIdxs = []int32{
	0, // 0: hazard.HazardDetection.DetectHazard:input_type -> hazard.ImageRequest
	1, // 1: hazard.HazardDetection.DetectHazard:output_type -> hazard.DetectionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hazard_hazard_proto_init() }
func file_hazard_hazard_proto_init() {
	if File_hazard_hazard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hazard_hazard_proto_rawDesc), len(file_hazard_hazard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hazard_hazard_proto_goTypes,
		DependencyIndexes: file_hazard_hazard_proto_depIdxs,
		MessageInfos:      file_hazard_hazard_proto_msgTypes,
	}.Build()
	File_hazard_hazard_proto = out.File
	file_hazard_hazard_proto_goTypes = nil
	file_hazard_hazard_proto_depIdxs = nil
}
